"""Build an independently versioned Claude guide from pinned upstream sources."""

from pathlib import Path
import re

from .io import digest, read_json


def build(root, check=False):
    root = Path(root)
    vendor = root / "vendor/claudish"
    lock = read_json(vendor / "source.json")
    for name, expected in lock["files"].items():
        if digest((vendor / name).read_bytes()) != expected:
            raise ValueError(f"Pinned upstream source changed: {name}")
    upstream = (vendor / "claudish-to-english.md").read_text()
    base = (root / "specs/claude-base.md").read_text()
    dictionary = read_json(root / "dictionary/claude.json")
    if set(dictionary) != {"upstream_slugs", "entries"}:
        raise ValueError("Claude dictionary needs upstream_slugs and entries")
    source = read_json(vendor / "entries.json")
    known = {item["slug"]: item for item in source["entries"]}
    known.update({item["id"]: item for item in source["phrase_guide"]})
    selected = dictionary["upstream_slugs"]
    if not isinstance(selected, list) or any(not isinstance(s, str) or s not in known for s in selected) or len(set(selected)) != len(selected):
        raise ValueError("Unknown or duplicate upstream dictionary slug")
    sections = [base.strip(), upstream.strip(), "## Contextual examples from the upstream dictionary\n\nThese illustrate meaning, not automatic word replacements."]
    for slug in selected:
        item = known[slug]
        sections.append(f"### {slug}\n\n{item['plain_english']}\n\n{item['explanation']}")
        for example in item.get("examples", [item["example"]] if "example" in item else []):
            sections.append(f"Before: {example['claudish']}\n\nAfter: {example['english']}")
    seen = set()
    if not isinstance(dictionary["entries"], list):
        raise ValueError("Entries must be a list")
    for item in dictionary["entries"]:
        fields = {"id", "guidance", "before", "after", "exceptions", "evidence", "example_origin"}
        if not isinstance(item, dict) or set(item) != fields:
            raise ValueError("Invalid Claude entry fields")
        if not isinstance(item["id"], str) or not re.fullmatch(r"[a-z][a-z0-9-]*", item["id"]) or item["id"] in seen:
            raise ValueError("Invalid or duplicate Claude entry ID")
        seen.add(item["id"])
        if any(not isinstance(item[key], str) or not item[key].strip() for key in ("guidance", "before", "after")):
            raise ValueError("Entry text must be nonempty")
        if item["example_origin"] != "synthetic":
            raise ValueError("Dictionary examples must be labelled synthetic")
        for key in ("exceptions", "evidence"):
            if not isinstance(item[key], list) or not item[key] or not all(isinstance(x, str) and x for x in item[key]):
                raise ValueError("Claude entries need exceptions and public evidence")
        for link in item["evidence"]:
            if not link.startswith("https://") and not (link.startswith("experiments/claude/") and (root / link.split("#")[0]).is_file()):
                raise ValueError("Evidence must be a public URL or Claude study record")
        sections.append(f"### {item['id']}\n\n{item['guidance']}\n\nBefore: {item['before']}\n\nAfter: {item['after']}\n\nExceptions: {' '.join(item['exceptions'])}")
    fingerprint = digest({"upstream": lock, "base": base, "dictionary": dictionary})
    text = f"<!-- Generated by python -m claudish build-claude-spec; inputs sha256:{fingerprint} -->\n\n" + "\n\n".join(sections) + "\n"
    target = root / "specs/claude-changes.md"
    if check:
        if not target.exists() or target.read_text() != text:
            raise ValueError("Claude guide is stale; run build-claude-spec")
    else:
        target.write_text(text)
    return {"spec": str(target), "sha256": digest(text), "input_sha256": fingerprint,
            "upstream_revision": lock["revision"], "entries": len(dictionary["entries"])}
