"""Build the installed spec directly from reviewed dictionary entries."""

from pathlib import Path
import re
import subprocess

from .io import digest, read_json


def tracked(root, name):
    """Whether Git has this file committed, so a reviewer can actually open it."""
    try:
        result = subprocess.run(["git", "-C", str(root), "ls-files", "--error-unmatch", name],
                                capture_output=True, text=True)
    except OSError:
        return (Path(root) / name).exists()
    if result.returncode == 0:
        return True
    if "not a git repository" in result.stderr.lower():
        return (Path(root) / name).exists()
    return False


# Fields that become spec text. The stamp covers these, so correcting a
# reviewer note never changes the guidance a frozen study was evaluated on.
RENDERED = ("id", "guidance", "before", "after", "exceptions")


def validate(entries, root=None):
    seen = set()
    required = {"id", "dimension", "guidance", "before", "after", "exceptions", "signals", "evidence", "example_origin"}
    if not isinstance(entries, list) or not entries:
        raise ValueError("Dictionary must be a nonempty list")
    for item in entries:
        if not isinstance(item, dict) or set(item) != required:
            raise ValueError(f"Dictionary entries must contain exactly {sorted(required)}")
        if not re.fullmatch(r"[a-z][a-z0-9-]*", item["id"]) or item["id"] in seen:
            raise ValueError("Dictionary IDs must be unique lowercase slugs")
        seen.add(item["id"])
        if item["dimension"] not in ("words", "structure", "simplicity", "meaning", "usefulness"):
            raise ValueError("Invalid dictionary dimension")
        for key in ("guidance", "before", "after"):
            if not isinstance(item[key], str) or not item[key].strip():
                raise ValueError(f"Missing dictionary field: {key}")
        for key in ("exceptions", "signals", "evidence"):
            if not isinstance(item[key], list) or not all(isinstance(x, str) and x for x in item[key]):
                raise ValueError(f"{key} must contain strings")
        if not item["exceptions"]:
            raise ValueError("Every rule needs at least one legitimate exception")
        if item["example_origin"] != "synthetic":
            raise ValueError("Illustrative rewrites must be labelled synthetic; put upstream references in evidence")
        for link in item["evidence"]:
            if link.startswith("https://"):
                continue
            if not link.startswith("experiments/"):
                raise ValueError("Evidence must link to a source or an experiment artifact")
            # A reviewer has to be able to open it, so the file must be committed.
            # Presence on disk is not enough: private run directories are ignored by Git.
            if root is not None and not tracked(root, link.split("#")[0]):
                raise ValueError(f"Evidence is not a committed file in this repository: {link}")
    return entries


def build(root, check=False):
    root = Path(root)
    base = (root / "specs/base.md").read_text()
    entries = validate(read_json(root / "dictionary/entries.json"), root)
    fingerprint = digest({"base": base,
                          "dictionary": [{key: entry[key] for key in RENDERED} for entry in entries]})
    sections = [f"<!-- Generated by python -m claudish build-spec; inputs sha256:{fingerprint} -->\n", base.rstrip()]
    for entry in entries:
        sections.append("\n".join([
            f"## {entry['id']}", "", entry["guidance"], "",
            f"Avoid: {entry['before']}", f"Prefer: {entry['after']}", "",
            "Exceptions: " + " ".join(entry["exceptions"]),
        ]))
    text = "\n\n".join(sections) + "\n"
    target = root / "specs/codex-comments.md"
    if check:
        if not target.exists() or target.read_text() != text:
            raise ValueError("Generated spec is stale; run python -m claudish build-spec")
    else:
        target.write_text(text)
    # The body hash excludes the provenance stamp, so a frozen study stays
    # verifiable across provenance corrections.
    return {"spec": str(target), "sha256": digest(text), "body_sha256": digest(text.split("\n", 1)[1]),
            "input_sha256": fingerprint, "entries": len(entries)}
