"""Build the installed spec directly from reviewed dictionary entries."""

from pathlib import Path
import re
import subprocess

from .io import digest, read_json


def tracked(root, name):
    """Whether Git has this file committed, so a reviewer can actually open it."""
    try:
        result = subprocess.run(["git", "-C", str(root), "ls-files", "--error-unmatch", name],
                                capture_output=True, text=True)
    except OSError:
        return (Path(root) / name).exists()
    if result.returncode == 0:
        return True
    if "not a git repository" in result.stderr.lower():
        return (Path(root) / name).exists()
    return False


# Fields that become spec text. The stamp covers these, so correcting a
# reviewer note never changes the guidance a frozen study was evaluated on.
RENDERED = ("id", "guidance", "before", "after", "exceptions")


def validate(entries, root=None):
    seen = set()
    required = {"id", "dimension", "guidance", "before", "after", "exceptions", "signals", "evidence", "example_origin"}
    if not isinstance(entries, list) or not entries:
        raise ValueError("Dictionary must be a nonempty list")
    for item in entries:
        if not isinstance(item, dict) or set(item) != required:
            raise ValueError(f"Dictionary entries must contain exactly {sorted(required)}")
        if not re.fullmatch(r"[a-z][a-z0-9-]*", item["id"]) or item["id"] in seen:
            raise ValueError("Dictionary IDs must be unique lowercase slugs")
        seen.add(item["id"])
        if item["dimension"] not in ("words", "structure", "simplicity", "meaning", "usefulness"):
            raise ValueError("Invalid dictionary dimension")
        for key in ("guidance", "before", "after"):
            if not isinstance(item[key], str) or not item[key].strip():
                raise ValueError(f"Missing dictionary field: {key}")
        for key in ("exceptions", "signals", "evidence"):
            if not isinstance(item[key], list) or not all(isinstance(x, str) and x for x in item[key]):
                raise ValueError(f"{key} must contain strings")
        if not item["exceptions"]:
            raise ValueError("Every rule needs at least one legitimate exception")
        if item["example_origin"] != "synthetic":
            raise ValueError("Illustrative rewrites must be labelled synthetic; put upstream references in evidence")
        for link in item["evidence"]:
            if link.startswith("https://"):
                continue
            if not link.startswith("experiments/"):
                raise ValueError("Evidence must link to a source or an experiment artifact")
            # A reviewer has to be able to open it, so the file must be committed.
            # Presence on disk is not enough: private run directories are ignored by Git.
            if root is not None and not tracked(root, link.split("#")[0]):
                raise ValueError(f"Evidence is not a committed file in this repository: {link}")
    return entries


def build(root, check=False):
    root = Path(root)
    base = (root / "specs/base.md").read_text()
    prose = (root / "specs/prose-base.md").read_text()
    entries = validate(read_json(root / "dictionary/entries.json"), root)
    fingerprint = digest({"base": base, "prose": prose,
                          "dictionary": [{key: entry[key] for key in RENDERED} for entry in entries]})
    sections = [base.rstrip(), prose.rstrip(), "## Comment examples\n\nThese examples are synthetic."]
    for entry in entries:
        sections.append("\n".join([
            f"### {entry['id']}", "", entry["guidance"], "",
            f"Before: {entry['before']}", f"After: {entry['after']}", "",
            "Exceptions: " + " ".join(entry["exceptions"]),
        ]))
    text = (f"<!-- Generated by python -m claudish build-spec; inputs sha256:{fingerprint} -->\n\n"
            + "\n\n".join(sections) + "\n")
    target = root / "specs/codex-comments.md"
    changes_base = (root / "specs/changes-base.md").read_text()
    changes_fingerprint = digest({"base": changes_base, "comments": fingerprint})
    changes_text = (f"<!-- Generated by python -m claudish build-spec; inputs sha256:{changes_fingerprint} -->\n\n"
                    + changes_base.rstrip() + "\n\n" + prose.rstrip()
                    + "\n\n## Comment-specific guidance\n\n"
                    + base.split("\n", 1)[1].strip() + "\n\n"
                    + "\n\n".join(sections[2:]) + "\n")
    changes_target = root / "specs/codex-changes.md"
    if check:
        for path, expected in ((target, text), (changes_target, changes_text)):
            if not path.exists() or path.read_text() != expected:
                raise ValueError(f"Generated spec is stale: {path}; run python -m claudish build-spec")
    else:
        target.write_text(text)
        changes_target.write_text(changes_text)
    # The body hash excludes the provenance stamp, so a frozen study stays
    # verifiable across provenance corrections.
    return {"spec": str(target), "sha256": digest(text), "body_sha256": digest(text.split("\n", 1)[1]),
            "input_sha256": fingerprint, "entries": len(entries),
            "changes_spec": str(changes_target), "changes_sha256": digest(changes_text),
            "changes_input_sha256": changes_fingerprint}
