"""Build the installed spec directly from reviewed dictionary entries."""

from pathlib import Path
import re

from .io import digest, read_json


def validate(entries):
    seen = set()
    required = {"id", "dimension", "guidance", "before", "after", "exceptions", "signals", "evidence", "example_origin"}
    if not isinstance(entries, list) or not entries:
        raise ValueError("Dictionary must be a nonempty list")
    for item in entries:
        if not isinstance(item, dict) or set(item) != required:
            raise ValueError(f"Dictionary entries must contain exactly {sorted(required)}")
        if not re.fullmatch(r"[a-z][a-z0-9-]*", item["id"]) or item["id"] in seen:
            raise ValueError("Dictionary IDs must be unique lowercase slugs")
        seen.add(item["id"])
        if item["dimension"] not in ("words", "structure", "simplicity", "meaning", "usefulness"):
            raise ValueError("Invalid dictionary dimension")
        for key in ("guidance", "before", "after"):
            if not isinstance(item[key], str) or not item[key].strip():
                raise ValueError(f"Missing dictionary field: {key}")
        for key in ("exceptions", "signals", "evidence"):
            if not isinstance(item[key], list) or not all(isinstance(x, str) and x for x in item[key]):
                raise ValueError(f"{key} must contain strings")
        if not item["exceptions"]:
            raise ValueError("Every rule needs at least one legitimate exception")
        if item["example_origin"] != "synthetic":
            raise ValueError("Illustrative rewrites must be labelled synthetic; put upstream references in evidence")
        if any(not x.startswith(("https://", "experiments/")) for x in item["evidence"]):
            raise ValueError("Evidence must link to a source or an experiment artifact")
    return entries


def build(root, check=False):
    root = Path(root)
    base = (root / "specs/base.md").read_text()
    entries = validate(read_json(root / "dictionary/entries.json"))
    fingerprint = digest({"base": base, "dictionary": entries})
    sections = [f"<!-- Generated by python -m claudish build-spec; inputs sha256:{fingerprint} -->\n", base.rstrip()]
    for entry in entries:
        sections.append("\n".join([
            f"## {entry['id']}", "", entry["guidance"], "",
            f"Avoid: {entry['before']}", f"Prefer: {entry['after']}", "",
            "Exceptions: " + " ".join(entry["exceptions"]),
        ]))
    text = "\n\n".join(sections) + "\n"
    target = root / "specs/codex-comments.md"
    if check:
        if not target.exists() or target.read_text() != text:
            raise ValueError("Generated spec is stale; run python -m claudish build-spec")
    else:
        target.write_text(text)
    return {"spec": str(target), "sha256": digest(text), "input_sha256": fingerprint, "entries": len(entries)}
